#!/usr/bin/env bash
### BEGIN INIT INFO
# Provides: metro-collector
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start daemon at boot time
# Description: Enable service provided by daemon.
### END INIT INFO

#--------------------------------------------------------------------------
# Author: Heung-Mook CHOI <hmchoi@unisem.co.kr>
# 2017/12/12, zorba
#--------------------------------------------------------------------------
#---------------------------------------------------------------------------
# # update-rc.d metro-collector defaults 90 05
# perl: warning: Setting locale failed.
# perl: warning: Please check that your locale settings:
#     LANGUAGE = "en_US:en",
#     LC_ALL = (unset),
#     LC_CTYPE = "UTF-8",
#     LANG = "en_US.UTF-8"
#     are supported and installed on your system.
# perl: warning: Falling back to the standard locale ("C").
#  Adding system startup for /etc/init.d/metro-collector ...
#    /etc/rc0.d/K05metro-collector -> ../init.d/metro-collector
#    /etc/rc1.d/K05metro-collector -> ../init.d/metro-collector
#    /etc/rc6.d/K05metro-collector -> ../init.d/metro-collector
#    /etc/rc2.d/S90metro-collector -> ../init.d/metro-collector
#    /etc/rc3.d/S90metro-collector -> ../init.d/metro-collector
#    /etc/rc4.d/S90metro-collector -> ../init.d/metro-collector
#    /etc/rc5.d/S90metro-collector -> ../init.d/metro-collector
#-----------------
# remove
# update-rc.d -f metro-collector remove
#---------------------------------------------------------------------------

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON_PATH=/opt/istanbul_metrobus/collector
DAEMON_NAME=metrobus_collector
DAEMON_ID=metrobus-collector-actor.jar
DAEMON_RUN=run-collector.sh

# Check that networking is up.
#[ ${NETWORKING} = "no" ] && exit 0

PATH=$PATH:$DAEMON_PATH

cd $DAEMON_PATH

# See how we were called.
case "$1" in
  start)
        # Start daemon.
        echo "Starting $DAEMON_NAME";
        pid=`ps ax | grep -i $DAEMON_ID | grep -v grep | awk '{print $1}'`
        if [ -n "$pid" ]
          then
          echo "$DAEMON_NAME is running"
        else
          nohup $DAEMON_PATH/$DAEMON_RUN 1>/dev/null 2>&1 &
        fi
        ;;
  stop)
        # Stop daemons.
        echo "Shutting down $DAEMON_NAME";
        pid=`ps ax | grep -i $DAEMON_ID | grep -v grep | awk '{print $1}'`
        if [ -n "$pid" ]
          then
          kill -9 $pid
        else
          echo "$DAEMON_NAME was not Running"
        fi
        ;;
  restart)
        $0 stop
        sleep 2
        $0 start
        ;;
  status)
        pid=`ps ax | grep -i $DAEMON_ID | grep -v grep | awk '{print $1}'`
        if [ -n "$pid" ]
          then
          echo "$DAEMON_NAME is Running as PID: $pid"
        else
          echo "$DAEMON_NAME is not Running"
        fi
        ;;
  *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
esac

exit 0
